/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps } from '@adonisjs/inertia/types'
import type IdentityUserDTransformer from '#app/identity/transformers/user.d'
import type IdentityUserTransformer from '#app/identity/transformers/user'
import type InertiaMiddleware from '#core/middleware/inertia_middleware'

export namespace Data {
  export namespace Identity {
    export type UserD = InferData<IdentityUserDTransformer>
    export namespace UserD {
      export type Variants = InferVariants<IdentityUserDTransformer>
    }
    export type User = InferData<IdentityUserTransformer>
    export namespace User {
      export type Variants = InferVariants<IdentityUserTransformer>
    }
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
}
