/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/app.js" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/bodyparser.js" />
/// <reference path="../../config/cors.js" />
/// <reference path="../../config/database.js" />
/// <reference path="../../config/encryption.js" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/session.js" />
/// <reference path="../../config/shield.js" />
