/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
	identity: {
		GetUser: () => import('#app/identity/controllers/get_user_controller'),
		SignIn: () => import('#app/identity/controllers/sign_in_controller'),
		SignOut: () => import('#app/identity/controllers/sign_out_controller'),
		SignUp: () => import('#app/identity/controllers/sign_up_controller'),
	},
}
