packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.7.2
  vite: ^7.1.7
  prettier: ^3.7.4
  eslint: ^9.28.0
  tailwindcss: ^4.0.6
  "@vitejs/plugin-react": ^5.0.4
  "@types/react": ^19.2.0
  "@types/react-dom": ^19.2.0
  "@types/node": ^22.10.2
  "unocss": "^66.5.12"
  "@tanstack/react-router": "^1.132.0"
  "@unpic/react": "^1.0.2"
