FROM node:22-bookworm-slim

# Install pnpm
RUN npm install -g pnpm

WORKDIR /app

# The code will be mounted via volume
CMD [ "sh", "-c", "pnpm install --config.ignore-scripts=false && pnpm --filter @apps/frontend dev --host" ]
