/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  identity: {
    RegisterD: () => import('#app/identity/controllers/register.d'),
    Register: () => import('#app/identity/controllers/register'),
  },
}
